### ISSUE TITLE
Reporty z harvestování lokálních katalogů

### ISSUE THREAD

**Issue by SmallhillCZ** [datagov-cz/nkod#14]
Představuju si to tak, že mi to ukáže nějaký číslo, kolik sad bylo nataženo, u kolika bylo varování a u kolika se vyskytla chyba. Ty not-OK kategorie se potom rozepíšou, takže uvidím, kde máme špatně datum, kde nám chybí popis atd.

Klidně jen mailem. Plus by se to mohlo publikovat jako datová sada Ministestva vnitra ;)

**Comment by jakubklimek** [comment]
Toto znamená významné rozšíření stávajícího procesu harvestování, který jde "optimisticky", čili co stáhne, to stáhne, případné chyby se nereportují, vadné záznamy se jen přeskakují. Je jasné, že toto by usnadnilo život správcům LKOD a pokusíme se to zahrnout do rozvoje NKOD.

**Comment by jakubklimek** [comment]
Vyřešeno extra validátorem LKOD (https://datagov-cz.github.io/lkod-validator/).
