### ISSUE TITLE
chybný typ dcat:spatialResolutionInMeters na výstupu NKOD

### ISSUE THREAD

**Issue by burespe1** [datagov-cz/nkod#32]
Požadavek na typ položky prostorové rozlišení v metrech dcat:spatialResolutionInMeters je `xsd:decimal`. 

![image](https://user-images.githubusercontent.com/43144398/201691689-1918aa1d-28c2-4cf4-9c7e-57ddac4a4aea.png)

NKOD nicméně na výstupu tutp položku předává jako `xsd:double`.

![image](https://user-images.githubusercontent.com/43144398/201690097-9786c81e-9b32-41eb-aaa8-d61eaefa6447.png)

dle vyjádření zástupců NKOD je toto problém způsobený v použitou knihovnou rdf4j, která v nasazené verzi samovolně změní reprezentaci čísla a tím i datový typ z `"12"^^xsd:decimal` na `"1.2E1"^^xsd:double`.

Problém se projeví jako chyba při vstupní kontrole v návazných katalozích a je potřeba ji opravit a to:
- odstrraněním této položky z NKOD a formuláře (stejně ji nikdo nepoužívá) či
- lokální opravou / patchem knihovny rfd4j

**Comment by jakubklimek** [comment]
Problém byl vyřešen upgradem rdf4j knihovny používané v NKOD.
