### ISSUE TITLE
Přidat odkaz na datovou sadu v LKOD

### ISSUE THREAD

**Issue by mordae** [datagov-cz/nkod#6]
Pokud má datová sada svou stránku v rámci LKOD, bylo by užitečné na ni odkazovat v NKOD.

**Comment by jakubklimek** [comment]
Toto by šlo rozdělit na 2 fáze
1) K registraci LKOD do NKOD přidat pole s odkazem na homepage LKOD. Tento odkaz může být zobrazován všude kde se mluví o poskytovateli dat.
2) Rozšířit katalogizační záznam každé datové sady o odkaz přímo na stránku dané datové sady v LKOD, což je o něco náročnější - je třeba toto generovat na straně LKODů

**Comment by jakubklimek** [comment]
Už nyní pro datové sady z lokálních katalogů v NKOD v datech existuje link na CKAN API package_show záznam v LKOD. Z IRI datové sady se na něj lze dostat cestou `^foaf:primaryTopic/dcterms:source`. To je ale spíše pro zájemce o originální strojově čitelný záznam, nikoliv na stránku pro uživatele.

**Comment by jakubklimek** [comment]
Aktuálně již NKOD obsahuje odkaz na homepage LKOD viz https://data.gov.cz/lokální-katalogy, pokud tuto možnost poskytovatel využije.
